### PR TITLE
Fix for Cairo plotting

### PR DESCRIPTION
**Pull request by Imoteph**
#39 

This should fix the problem with cairo pixel size limit. If cairo should be used, add `--graph` to the script.

### CODE REVIEW

**Comment by hvaret** [comment]
Hi,

thanks for the improvements and the pull request. I think there is a typo in the carioSizeWrapper() function you created, could you please name it cairoSizeWrapper()?

Then, as "cairo" is the default for the bitmapType option I am not sure to understand the new "graph" parameter in SARTools, could you please explain me how it is expected to work? Maybe we could remove it as well as the "options(bitmapType="cairo")"?

Moreover, could you create the pull request on the development branch of SARTools such that I can perform some tests on my side?

Thanks again,

Hugo

**Comment by Imoteph** [comment]
Hi Hugo

- Fix typo

- I changed the behavior now to completely "TRUE" and "FALSE"   

I hope that I understood you correctly:

At least here for us, when we were using SARTools, "cairo" was not the default behavior. 

Hence, I added this but only as an option to allow backwards compatibility if this just a local problem ( if you have missing x or other external plotting dependencies as described from the Cairo package). But then I run into the problem that sometimes images were pixel-wise bigger than the accepted size from Cairo standard. 

> Cairo graphics device that can be use to create high-quality vector (PDF, PostScript and SVG) and bitmap output (PNG,JPEG,TIFF), and high-quality rendering in displays (X11 and Win32). Since it uses the same back-end for all output, copying across formats is WYSIWYG. Files are created without the dependence on X11 or other external 

Hope that helped

**Comment by hvaret** [comment]
Thanks for the details, I now understand your problem.

I still see the "cario" typo in the files changed, maybe you forgot to commit?

Then the "graph" parameter might be not very informative, could you please change it to "forceCairoGraph" with FALSE value by default?

Best,

Hugo

**Comment by Imoteph** [comment]
yep sry, I missed on push!

- changes graph to forceCairoGraph   (default false)


best

vipul

**Comment by hvaret** [comment]
Hi,
thanks for these last changes. I am going to merge with the development branch and check that all is OK before merging with the master branch.
Best,
Hugo

**Pull request merged**
